# Generated by Django 5.0.6 on 2024-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Code")),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Code")),
                (
                    "broker",
                    models.CharField(choices=[("alpaca", "Alpaca")], default=None),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.JSONField(verbose_name="Preset")),
                (
                    "indicators",
                    models.ManyToManyField(
                        related_name="indicators", to="midas.indicator"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_conditions",
                    models.ManyToManyField(to="midas.indicatorcondition"),
                ),
                (
                    "leads",
                    models.ManyToManyField(
                        related_name="screener_leads", to="midas.symbol"
                    ),
                ),
                (
                    "symbols",
                    models.ManyToManyField(
                        related_name="screener_symbols",
                        to="midas.symbol",
                        verbose_name="Watchlist",
                    ),
                ),
            ],
        ),
    ]
