# Generated by Django 5.0.6 on 2024-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0002_indicatorcondition_code_scanner_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(default=None, verbose_name="Exchange"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="json",
            field=models.JSONField(default=None, max_length=50, verbose_name="Json"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="name",
            field=models.CharField(default="None", max_length=50, verbose_name="Name"),
        ),
    ]
