# Generated by Django 5.0.6 on 2024-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0003_symbol_exchange_symbol_json_symbol_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=models.CharField(
                default="None", max_length=1023, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="indicatorcondition",
            name="code",
            field=models.CharField(
                default="None", max_length=1023, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="name",
            field=models.CharField(
                default="None", max_length=1023, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="code",
            field=models.CharField(max_length=1023, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="json",
            field=models.JSONField(default=None, max_length=1023, verbose_name="Json"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name",
            field=models.CharField(
                default="None", max_length=1023, verbose_name="Name"
            ),
        ),
    ]
