# Generated by Django 5.0.6 on 2024-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0004_alter_indicator_code_alter_indicatorcondition_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanner",
            name="indicator_conditions",
            field=models.ManyToManyField(blank=True, to="midas.indicatorcondition"),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="leads",
            field=models.ManyToManyField(
                blank=True, related_name="screener_leads", to="midas.symbol"
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="symbols",
            field=models.ManyToManyField(
                blank=True,
                related_name="screener_symbols",
                to="midas.symbol",
                verbose_name="Watchlist",
            ),
        ),
    ]
