# Generated by Django 5.0.6 on 2024-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0005_alter_scanner_indicator_conditions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="group",
            field=models.CharField(max_length=1023, null=True, verbose_name="Group"),
        ),
        migrations.AddField(
            model_name="indicator",
            name="lib",
            field=models.CharField(max_length=1023, null=True, verbose_name="Library"),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=models.CharField(max_length=1023, null=True, verbose_name="Code"),
        ),
    ]
