# Generated by Django 5.0.6 on 2024-06-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0006_indicator_group_indicator_lib_alter_indicator_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatorcondition",
            name="indicators",
        ),
        migrations.AddField(
            model_name="indicatorcondition",
            name="name",
            field=models.CharField(blank=True, max_length=1023, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=models.CharField(
                blank=True, max_length=1023, null=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="group",
            field=models.CharField(
                blank=True, max_length=1023, null=True, verbose_name="Group"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="lib",
            field=models.CharField(
                blank=True, max_length=1023, null=True, verbose_name="Library"
            ),
        ),
        migrations.AlterField(
            model_name="indicatorcondition",
            name="code",
            field=models.CharField(blank=True, max_length=1023, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="name",
            field=models.CharField(max_length=1023, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="IndicatorInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=1023, unique=True, verbose_name="Slug"),
                ),
                ("setup", models.JSONField(verbose_name="setup")),
                ("code", models.TextField(blank=True, verbose_name="Code")),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="midas.indicator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="indicatorcondition",
            name="indicator_instances",
            field=models.ManyToManyField(blank=True, to="midas.indicatorinstance"),
        ),
        migrations.AddField(
            model_name="scanner",
            name="indicator_instances",
            field=models.ManyToManyField(blank=True, to="midas.indicatorinstance"),
        ),
    ]
