# Generated by Django 5.0.6 on 2024-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0007_remove_indicatorcondition_indicators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorinstance",
            name="setup",
            field=models.JSONField(blank=True, verbose_name="setup"),
        ),
    ]
