# Generated by Django 5.0.6 on 2024-06-06 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0008_alter_indicatorinstance_setup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatorinstance",
            name="slug",
        ),
    ]
