# Generated by Django 5.0.6 on 2024-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0009_remove_indicatorinstance_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorinstance",
            name="name",
            field=models.SlugField(
                default="default", max_length=1023, unique=True, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
