# Generated by Django 5.0.6 on 2024-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("midas", "0011_alter_indicatorinstance_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorinstance",
            name="options",
            field=models.TextField(blank=True, null=True, verbose_name="Options"),
        ),
    ]
