# Generated by Django 5.0.6 on 2024-10-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0013_index_alter_indicatorinstance_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='indexes',
            field=models.ManyToManyField(to='midas.index', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='index',
            name='ticker',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Ticker'),
        ),
    ]
