# Generated by Django 5.0.6 on 2024-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0015_industry_alter_symbol_indexes_symbol_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='Log'),
        ),
    ]
