# Generated by Django 5.0.6 on 2024-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0017_scanner_index_scanner_status_scanner_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='strategy',
            field=models.CharField(blank=True, choices=[('panda', 'Panda'), ('cat', 'Cat')], null=True),
        ),
    ]
