# Generated by Django 5.0.6 on 2024-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0019_scanner_time_frame_alter_scanner_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='broker',
            field=models.CharField(choices=[('alpaca', 'Alpaca')], default='alpaca'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(blank=True, default=None, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='industry_index', to='midas.industry', verbose_name='industries'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='json',
            field=models.JSONField(blank=True, default=None, max_length=1023, verbose_name='Json'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(default=None, max_length=1023, verbose_name='Name'),
        ),
    ]
