# Generated by Django 5.0.6 on 2024-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0021_scannerrun_remove_scanner_strategy_scanner_algo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='algo',
            field=models.CharField(blank=True, choices=[('Panda', 'Momentum Panda'), ('Cat', 'Deep Cat'), ('Coyote', 'Coyote')], null=True),
        ),
    ]
