# Generated by Django 5.0.6 on 2024-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0023_alter_symbol_exchange_alter_symbol_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='algo',
            field=models.CharField(blank=True, choices=[('algos.Panda', 'Momentum Panda'), ('Cat', 'Deep Cat'), ('Coyote', 'Coyote')], null=True),
        ),
        migrations.AlterField(
            model_name='scannerrun',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
